<img src="IMAGES_PYTHON_COURSE_2018/LOGO_MEINBIO_TRANSPARENT.png" width="200" height="200" />
# <center>Python course 2018
### <center>MeInBio Training Group
#### <center> by Florian Heyl & Francesco Ferrari 
Welcome to this introduction to Python. 


# PART : NUMPY

## Exercise 1: Introduction

Numpy is one of the most important packages for python. Packages are collections of classes and functions that can be imported into a python script. Only when you import certain packages, you are allowed to use specific functions. the keyword **import** can be used to import a package. 

In [1]:
import numpy

a = numpy.array([2,3,4])
print(a)

[2 3 4]


As you can see we defined a new array **a** which is equivalent to a list in python. However, in order to use an numpy array we specifically have to say where the class **array** comes from. The package (or scope) is our package numpy. So what happens if we don't specifiy the scope.

In [2]:
a = array([2,3,4])

NameError: name 'array' is not defined

You see, that python doesn't know the class **array** since it is not defined in the basic class package.

Ok, actually writing allways **numpy.** for every class that is definined in numpy might be really laborious. However, we can redifine the package name with:

In [4]:
import numpy as np

a = np.array([2,3,4])
print(a)

[2 3 4]


As you can see, this is way faster. The only thing is, that you have to remember what **np** stands for.

## Exercise 2: Why do we have to use numpy?

Numpy is a very powerful package that make arithmatically calculation easier and more handy. Lets give you an example:

### TASK

Add the two vectors together in the best way you can think of **without using numpy**: 

In [6]:
a = [1,2,3]
b = [4,5,6]

### put your code here

You may have realised that certain things are not as intutive in python as it seems, especially when it comes to arithmetically stuff. Intuitively, you would think that a simple summation like **a+b** would do it, but this just concatenates the two lists together. Therefore, numpy is our savior. 

### TASK

Define the two vectors above as **numpy.array**(s) and simply do a summation (**a+b**).

In [7]:
### put your code here

Again, numpy is our savior when it comes to mathematical stuff. Lets do another task this time with a higher dimension. Lets say we want to substract two matrices, we first have to learn how to define a matrix:

In [11]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(a[0,0])
print(a[1,0])
print(a[0,1])

print(a[0,:])
print(a[:,1])

1
4
2
[1 2 3]
[2 5 8]


A matrix is just a two dimensional object with row (i) and columns (j). As you can see, **a** holds a matrix with three rows and three columns. Getting one specific cell out of the matrix, then I have to use the snythax **a[i,j]**. The last to lines then gives me the first row and the seconds column. The symbol **:** indicates that I go over ever element. 

### TASK
Lets return to our task and simply substract the two defined matrices from each other:

In [13]:
a = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
b = np.array([[1,2,3],
              [1,2,3],
              [1,2,3]])

### put your code here

## Exercise 3: Other things you can do in numpy?

Python has certain other usefull operations you can only do with numpy. For example:

### TASK

Write a loop that finds the maximum of the given list **a** and print the index of this elemnts **without numpy**.

In [14]:
a = [6,10,2,22,305,103,1,0,56,110,102,255,10,310,3,1,5,7,309,206]

### put your code here

With numpy this is a very easy task.

In [1]:
i = np.argmax(a)
print(a[i])
print(i)

NameError: name 'np' is not defined

### TASK

a) Write a functions that calculates you the mean of the list **a** wihout numpy. 
b) Find an equivalent function for numpy.

In [2]:
### put your code here for (a)


### put your code here for (b)



### TASK

Find a function in numpy that calculates you the standard deviation of the list **a**.

In [3]:
### put your code here